# Setup
title: 阳龙生的博客
description: 三十功名尘与土，十万代码云和月
url: https://yanglongsheng.blog.csdn.net/
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: yanglonghseng
  card: summary
logo: logo.png
social:
  name: longsheng yang
  links:
    - https://twitter.com/yanglongsheng
    - https://github.com/yanglongsheng
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: longsheng yang
  url: https://github.com/yanglongsheng/
  email: yanglongsheng.yls@gmail.com
